### ISSUE TITLE
Cannot compile with Erlang version 18 [JIRA: RIAK-2055]

### ISSUE THREAD

**Issue by zack-bitcoin** [basho/cuttlefish#196] opened 2015-07-29 23:27 UTC
Can I help you upgrade to support 18? Does it involve a lot of work?

**Comment by macintux** [comment] 2015-07-30 13:50
To my knowledge no one has taken a look at the problem yet, so I don't know how much work it'll take. The fact that it builds cleanly is encouraging.

Thanks for asking; let me poke a bit and I'll be back in touch.

**Comment by trevorriles** [comment] 2015-07-30 14:03
I just took a look, I looks like the issue is with neotoma. It seems to have been fixed on the master branch.

What is happening is neotoma is generating some erlang code that uses `list_to_binary` and should instead be using `unicode:characters_to_binary`.

I have made a request to get a new version released: https://github.com/seancribbs/neotoma/issues/37

**Comment by macintux** [comment] 2015-07-30 14:08
Thanks, that does look promising. That particular test fails with 17 as well, unsurprisingly, so I'd wager cuttlefish works under 18.0, although caution is warranted.

**Comment by trevorriles** [comment] 2015-07-30 14:11
So my branch name is misleading. I don't currently only have 18 installed so have not had a chance to test other versions.

**Comment by macintux** [comment] 2015-07-30 14:17
@tburghart created a [branch for 17](https://github.com/basho/cuttlefish/tree/feature/otp-17) previously; I've asked him about the other `rebar.config` changes.

**Comment by trevorriles** [comment] 2015-07-30 14:31
1.7.3 tagged for neotoma I will update the branch.

**Closed as completed** 2015-08-04 15:24 UTC
Labels: JIRA: To Do

**Comment by trevorriles** [comment] 2015-08-04 20:18
@macintux: Should we tag a new version with this fix?

**Comment by macintux** [comment] 2015-08-04 20:20
I’m working on closing out existing PRs before rolling a new version.

-John
